# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CoreferenceResolver/CorefCluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CoreferenceResolver/CorefCluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CoreferenceResolver import Mention_pb2 as CoreferenceResolver_dot_Mention__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&CoreferenceResolver/CorefCluster.proto\x12\x19\x41tlas.CoreferenceResolver\x1a!CoreferenceResolver/Mention.proto\"|\n\x0c\x43orefCluster\x12\x34\n\x08mentions\x18\x01 \x03(\x0b\x32\".Atlas.CoreferenceResolver.Mention\x12\x36\n\nantecedent\x18\x02 \x01(\x0b\x32\".Atlas.CoreferenceResolver.MentionB\x1f\xaa\x02\x1c\x41tlas.Core.Clients.Generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoreferenceResolver.CorefCluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034Atlas.Core.Clients.Generated'
  _globals['_COREFCLUSTER']._serialized_start=104
  _globals['_COREFCLUSTER']._serialized_end=228
# @@protoc_insertion_point(module_scope)
