# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CoreferenceResolver/CoreferenceResponse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CoreferenceResolver/CoreferenceResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CoreferenceResolver import CorefCluster_pb2 as CoreferenceResolver_dot_CorefCluster__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-CoreferenceResolver/CoreferenceResponse.proto\x12\x19\x41tlas.CoreferenceResolver\x1a&CoreferenceResolver/CorefCluster.proto\"P\n\x13\x43oreferenceResponse\x12\x39\n\x08\x63lusters\x18\x01 \x03(\x0b\x32\'.Atlas.CoreferenceResolver.CorefClusterB\x1f\xaa\x02\x1c\x41tlas.Core.Clients.Generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoreferenceResolver.CoreferenceResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034Atlas.Core.Clients.Generated'
  _globals['_COREFERENCERESPONSE']._serialized_start=116
  _globals['_COREFERENCERESPONSE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
