# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CoreferenceResolver/CoreferenceResolver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'CoreferenceResolver/CoreferenceResolver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from CoreferenceResolver import CoreferenceRequest_pb2 as CoreferenceResolver_dot_CoreferenceRequest__pb2
from CoreferenceResolver import CoreferenceResponse_pb2 as CoreferenceResolver_dot_CoreferenceResponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-CoreferenceResolver/CoreferenceResolver.proto\x12\x19\x41tlas.CoreferenceResolver\x1a,CoreferenceResolver/CoreferenceRequest.proto\x1a-CoreferenceResolver/CoreferenceResponse.proto2\x8b\x01\n\x13\x43oreferenceResolver\x12t\n\x13ResolveCoreferences\x12-.Atlas.CoreferenceResolver.CoreferenceRequest\x1a..Atlas.CoreferenceResolver.CoreferenceResponseB\x1f\xaa\x02\x1c\x41tlas.Core.Clients.Generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoreferenceResolver.CoreferenceResolver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034Atlas.Core.Clients.Generated'
  _globals['_COREFERENCERESOLVER']._serialized_start=170
  _globals['_COREFERENCERESOLVER']._serialized_end=309
# @@protoc_insertion_point(module_scope)
