# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from CoreferenceResolver import CoreferenceRequest_pb2 as CoreferenceResolver_dot_CoreferenceRequest__pb2
from CoreferenceResolver import CoreferenceResponse_pb2 as CoreferenceResolver_dot_CoreferenceResponse__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in CoreferenceResolver/CoreferenceResolver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreferenceResolverStub(object):
    """Resolves coreferences in text, identifying mentions that refer to the same entity. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveCoreferences = channel.unary_unary(
                '/Atlas.CoreferenceResolver.CoreferenceResolver/ResolveCoreferences',
                request_serializer=CoreferenceResolver_dot_CoreferenceRequest__pb2.CoreferenceRequest.SerializeToString,
                response_deserializer=CoreferenceResolver_dot_CoreferenceResponse__pb2.CoreferenceResponse.FromString,
                _registered_method=True)


class CoreferenceResolverServicer(object):
    """Resolves coreferences in text, identifying mentions that refer to the same entity. 
    """

    def ResolveCoreferences(self, request, context):
        """Analyzes text and returns coreference clusters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreferenceResolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveCoreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveCoreferences,
                    request_deserializer=CoreferenceResolver_dot_CoreferenceRequest__pb2.CoreferenceRequest.FromString,
                    response_serializer=CoreferenceResolver_dot_CoreferenceResponse__pb2.CoreferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Atlas.CoreferenceResolver.CoreferenceResolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Atlas.CoreferenceResolver.CoreferenceResolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreferenceResolver(object):
    """Resolves coreferences in text, identifying mentions that refer to the same entity. 
    """

    @staticmethod
    def ResolveCoreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Atlas.CoreferenceResolver.CoreferenceResolver/ResolveCoreferences',
            CoreferenceResolver_dot_CoreferenceRequest__pb2.CoreferenceRequest.SerializeToString,
            CoreferenceResolver_dot_CoreferenceResponse__pb2.CoreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
