from CoreferenceResolver import CoreferenceRequest_pb2 as _CoreferenceRequest_pb2
from CoreferenceResolver import CoreferenceResponse_pb2 as _CoreferenceResponse_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
