# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Narrator import DocumentRequest_pb2 as Narrator_dot_DocumentRequest__pb2
from Narrator import RelationshipResponse_pb2 as Narrator_dot_RelationshipResponse__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Narrator/Narrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NarratorStub(object):
    """Extracts relationships from the given stream of documents and returns a stream of relationships.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRelationships = channel.unary_stream(
                '/Atlas.Narrator.Narrator/GetRelationships',
                request_serializer=Narrator_dot_DocumentRequest__pb2.DocumentRequest.SerializeToString,
                response_deserializer=Narrator_dot_RelationshipResponse__pb2.RelationshipResponse.FromString,
                _registered_method=True)


class NarratorServicer(object):
    """Extracts relationships from the given stream of documents and returns a stream of relationships.
    """

    def GetRelationships(self, request, context):
        """Extracts relationships from the given stream of documents and returns a stream of relationships.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NarratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRelationships': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRelationships,
                    request_deserializer=Narrator_dot_DocumentRequest__pb2.DocumentRequest.FromString,
                    response_serializer=Narrator_dot_RelationshipResponse__pb2.RelationshipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Atlas.Narrator.Narrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Atlas.Narrator.Narrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Narrator(object):
    """Extracts relationships from the given stream of documents and returns a stream of relationships.
    """

    @staticmethod
    def GetRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Atlas.Narrator.Narrator/GetRelationships',
            Narrator_dot_DocumentRequest__pb2.DocumentRequest.SerializeToString,
            Narrator_dot_RelationshipResponse__pb2.RelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
