# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Narrator/Narrator.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'Narrator/Narrator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Narrator import DocumentRequest_pb2 as Narrator_dot_DocumentRequest__pb2
from Narrator import RelationshipResponse_pb2 as Narrator_dot_RelationshipResponse__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Narrator/Narrator.proto\x12\x0e\x41tlas.Narrator\x1a\x1eNarrator/DocumentRequest.proto\x1a#Narrator/RelationshipResponse.proto2g\n\x08Narrator\x12[\n\x10GetRelationships\x12\x1f.Atlas.Narrator.DocumentRequest\x1a$.Atlas.Narrator.RelationshipResponse0\x01\x42\x1f\xaa\x02\x1c\x41tlas.Core.Clients.Generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Narrator.Narrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034Atlas.Core.Clients.Generated'
  _globals['_NARRATOR']._serialized_start=112
  _globals['_NARRATOR']._serialized_end=215
# @@protoc_insertion_point(module_scope)
