# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Narrator/Phrase.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Narrator/Phrase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15Narrator/Phrase.proto\x12\x0e\x41tlas.Narrator\"<\n\x06Phrase\x12\x12\n\nstartIndex\x18\x01 \x01(\x05\x12\x10\n\x08\x65ndIndex\x18\x02 \x01(\x05\x12\x0c\n\x04text\x18\x03 \x01(\tB\x1f\xaa\x02\x1c\x41tlas.Core.Clients.Generatedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Narrator.Phrase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034Atlas.Core.Clients.Generated'
  _globals['_PHRASE']._serialized_start=41
  _globals['_PHRASE']._serialized_end=101
# @@protoc_insertion_point(module_scope)
